services:
  - type: web
    name: quantum-dynamics
    runtime: python
    buildCommand: cd app && rm -f db.sqlite3 && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: bash app/start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "true"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
