# Generated by Django 5.2.16 on 2026-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('studies', models.CharField(max_length=200, verbose_name='filière / études')),
                ('motivation', models.TextField(verbose_name='motivation')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='nouveau', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('category', models.CharField(choices=[('pv', 'Procès-verbal'), ('ag', 'Assemblée générale'), ('partenariat', 'Partenariat'), ('comptabilite', 'Comptabilité'), ('divers', 'Divers')], default='divers', max_length=20, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file_name', models.CharField(max_length=255, verbose_name='nom du fichier')),
                ('file_data', models.BinaryField(verbose_name='données du fichier')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('role', models.CharField(max_length=120, verbose_name='rôle')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('photo_url', models.URLField(blank=True, verbose_name='photo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('edition', models.PositiveIntegerField(default=1, verbose_name="numéro d'édition")),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('file_name', models.CharField(max_length=255, verbose_name='nom du fichier')),
                ('file_data', models.BinaryField(verbose_name='données du fichier')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('published_at', models.DateField(verbose_name='publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'ordering': ['-published_at', '-edition'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='clé')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='compteur')),
                ('window_start', models.DateTimeField(verbose_name='début de fenêtre')),
            ],
        ),
    ]
