# Generated by Django 4.2.30 on 2026-08-09 22:27

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_newsletter_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('summary', models.CharField(max_length=300, verbose_name='accroche')),
                ('description', models.TextField(verbose_name='description')),
                ('domaine', models.CharField(choices=[('transports', 'Transports'), ('industrie', 'Industrie'), ('energie', 'Énergie')], max_length=20, verbose_name='domaine')),
                ('statut', models.CharField(choices=[('idee', 'Idée'), ('en_cours', 'En cours'), ('prototype', 'Prototype'), ('competition', 'En compétition'), ('termine', 'Terminé')], default='idee', max_length=20, verbose_name='statut')),
                ('cover', models.ImageField(blank=True, upload_to=core.models._image_upload_to, verbose_name='image de couverture')),
                ('cover_size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('published_at', models.DateField(verbose_name='publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'ordering': ['display_order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models._image_upload_to, verbose_name='image')),
                ('image_size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.project')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
